import Footer from "./Components/Layout/Footer";
import Header from "./Components/Layout/Header";
import "./globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";



export const metadata = {
  title: "Sam Technical Service Contracting EST",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="pageWrapper">
        <Header />
        {children}
        <Footer />
        </div>
      </body>
    </html>
  );
}
